apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter

  template:
    metadata:
      labels:
        app: node-exporter

    spec:
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:latest
        args:
          - "--path.rootfs=/host"
          - "--web.config.file=/etc/node-exporter/web.yaml"  

        ports:
        - containerPort: 9100
          name: metrics

        volumeMounts:                     
        - name: web-config                
          mountPath: /etc/node-exporter/ 
          readOnly: true

      volumes:
      - name: web-config
        configMap:
          name: node-exporter-web
