apiVersion: v1
data:
  web-config: YmFzaWNfYXV0aF91c2VyczoKICBhZG1pbjogJDJ5JDEwJGk5UFRWbWoxaWRuTjB0MW9lS0hrOGUzTXB0TTY4Rzk5V3R2YTR0aUNWSE9BVEdKdFFqbC9p
kind: Secret
metadata:
  name: basic-auth1
  namespace: monitoring
type: Opaque
